### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by florianschiel** [IPS-LMU/The-EMU-SDMS-Manual#1]
Link to course material/book: (https://ips-lmu.github.io/A_Course_In_The_EMU-SDMS/)[https://ips-lmu.github.io/A_Course_In_The_EMU-SDMS/]

... does not work for me (404).

**Comment by raphywink** [comment]
About to either delete or make this repo private again anyway... it is far from something I want people to look at right now. However, in future I think we'll publish a course plus the EMU Manual this way! See here for an example: http://r4ds.had.co.nz/ of such a book.

**Comment by raphywink** [comment]
Oh just FYI: the reason I made it public was because of travis-ci.
