### ISSUE TITLE
Section heading incorrectly parsed

### ISSUE THREAD

**Issue by stefanocoretta** [IPS-LMU/The-EMU-SDMS-Manual#7]
https://github.com/IPS-LMU/The-EMU-SDMS-Manual/blob/16a74543c5465a75d5555ad602509e19424bb3eb/emu-webApp.Rmd#L55

First off, EMU-SDMS is awesome, and this manual is awesome. Great job! 💘

In the [compiled manual](https://ips-lmu.github.io/The-EMU-SDMS-Manual/chap-emu-webApp.html#sec:emu-webApp-mainLayout), the label is incorrectly parsed as part of the heading rather than as pandoc markup.

The line should read `#### Segments and events {-#segments-events}`.

**Comment by raphywink** [comment]
Thanks for this and also for the compliments :-)! Will be in the next compiled version... (that reminds me... I should probably add a NEWS.md with version numbers of the manual... hmmm)
