### ISSUE TITLE
Crossreference not parsed

### ISSUE THREAD

**Issue by stefanocoretta** [IPS-LMU/The-EMU-SDMS-Manual#8]
https://github.com/IPS-LMU/The-EMU-SDMS-Manual/blob/16a74543c5465a75d5555ad602509e19424bb3eb/overview.Rmd#L48

I am not sure why, but the cross-reference `\@ref(chap:annot_struct_mod)` is not parsed in the [overview chapter](https://ips-lmu.github.io/The-EMU-SDMS-Manual/chap-overview.html).

**Comment by raphywink** [comment]
I had to change all tex refs containing underscores to - as md/Rmd doesn't like underscores in refs. Must have missed that one. Thanks for pointing it out :-)
